services:
- docker

script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t $DOCKER_USERNAME/openvas-docker-lite:20.8.0 -t $DOCKER_USERNAME/openvas-docker-lite .
- docker push $DOCKER_USERNAME/openvas-docker-lite
